- hosts: localhost
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
  become: true
  strategy: linear
  serial: 1
  gather_facts: no

  tasks:
  
  - name: install Yum utils
    yum:
      name: yum-utils
      state: present

  - name: add Docker repo
    shell: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
    args:
      creates: /etc/yum.repos.d/docker-ce.repo

  - name: install Docker
    yum:
      name: docker-ce,docker-ce-cli,containerd.io,libseccomp
      state: latest

  - name: start Docker service
    service:
      name: docker
      state: started
      enabled: yes

  - name: upgrade pip
    pip:
      name: pip
      state: latest

  - name: pip docker module
    pip:
      name: docker
      state: latest
    
  - name: setup Docker Swarm
    docker_swarm:
      state: present

  - name: install docker-compose
    pip:
      name: docker-compose
      state: latest
  
  - name: install jsondiff
    pip:
      name: jsondiff
      state: latest

  - name: store docker secret
    docker_secret:
      name: pg_pass
      data: '%R$#D$#TR'
      state: present
      
  - name: import compose definition
    include_vars:
      file: docker-compose.yaml
      name: compose_definition
      
  - name: bootstrap docker-compose
    docker_stack:
      name: oracle
      compose: 
      - "{{ compose_definition }}"
      state: present